import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

interface RequestBody {
  prompt: string;
  apiKey: string;
}

Deno.serve(async (req: Request) => {
  // Gestion des requêtes CORS (pour que le navigateur accepte la réponse)
  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 200,
      headers: corsHeaders,
    });
  }

  try {
    const { prompt, apiKey }: RequestBody = await req.json();

    if (!prompt || !apiKey) {
      return new Response(
        JSON.stringify({ error: 'Missing prompt or apiKey' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Appel à l'API Google Gemini (Imagen 3)
    // Endpoint officiel pour la génération d'image via Gemini
    // Note: "imagen-3.0-generate-001" est le modèle actuel, sujet à évolution
    const url = `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict?key=${apiKey}`;

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        instances: [
          { prompt: prompt }
        ],
        parameters: {
          sampleCount: 1,
          aspectRatio: "1:1", // Carré pour Instagram/Meta
          personGeneration: "allow_adult", // Autorise les personnes réalistes
        }
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Google API error:', errorText);
      return new Response(
        JSON.stringify({ error: `Google API Error: ${response.statusText} - ${errorText}` }),
        { status: response.status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const data = await response.json();

    // L'API Google renvoie l'image en base64, pas en URL.
    // Nous devons la renvoyer telle quelle au front, ou l'uploader sur Supabase Storage.
    // Pour l'instant, on renvoie le base64 directement pour affichage immédiat.
    
    if (!data.predictions || !data.predictions[0]?.bytesBase64Encoded) {
       throw new Error('No image generated by Google API');
    }

    const base64Image = data.predictions[0].bytesBase64Encoded;
    // On formate en Data URL pour que le frontend puisse l'afficher directement dans <img src="..." />
    const imageUrl = `data:image/png;base64,${base64Image}`;

    return new Response(
      JSON.stringify({ url: imageUrl }), // On garde le format { url: ... } pour être compatible avec le reste du code
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});